services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=k-cards

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../frontend/k-card-inicio:/usr/share/nginx/html:ro
